### ISSUE TITLE
How to export data from learnpress 2 for learnpress 3?

### ISSUE THREAD

**Issue by adriancoliveira** [LearnPress/LearnPress-Import-Export#1]
I need to export data from a website with learnpress 2 to a website with learnpress 3, but I can not import the file generated in the export of version 2 of the plugin.

**Comment by halink0803** [comment]
@codiworks This repository has not updated for 2 years now, I don't think they continue support on this channel. You should contact them at https://thimpress.com/product/wordpress-lms-plugin-learnpress/. Good luck.

**Comment by adriancoliveira** [comment]
Thanks @halink0803 , i'll contact them.
